name: JVote
version: 1.0.0
main: com.wkaye.jvote.JVote
authors: [ xXGunner989Xx ]
description: A weather voting plugin for Minecraft Beta 1.7.3 designed for Project Poseidon w/ Fundamentals
commands:
  vote:
    description: a vote command to change weather or time
    usage: "/<command> <arg>"
